// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "gettext.h"
#include "wkey_dialogs.h"
#include "support.h"
#include "xmlrpc_rig.h"

Fl_ComboBox *selectCommPort=(Fl_ComboBox *)0;

Fl_Input *inpXmlAddress=(Fl_Input *)0;

static void cb_inpXmlAddress(Fl_Input* o, void*) {
  progStatus.log_address = o->value();
}

Fl_Input *inpXmlPort=(Fl_Input *)0;

static void cb_inpXmlPort(Fl_Input* o, void*) {
  progStatus.log_port = o->value();
}

Fl_Return_Button *btn_ser_port_ok=(Fl_Return_Button *)0;

static void cb_btn_ser_port_ok(Fl_Return_Button*, void*) {
  cbOkSetupDialog();
}

Fl_Button *btn_serial_port_cancel=(Fl_Button *)0;

static void cb_btn_serial_port_cancel(Fl_Button*, void*) {
  cbCancelSetupDialog();
}

Fl_Double_Window* SetupDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(270, 145, _("Select Ports"));
    w = o;
    { selectCommPort = new Fl_ComboBox(75, 13, 190, 23, _("Ser. Port"));
      selectCommPort->tooltip(_("Xcvr serial port"));
      selectCommPort->box(FL_DOWN_BOX);
      selectCommPort->color((Fl_Color)53);
      selectCommPort->selection_color(FL_BACKGROUND_COLOR);
      selectCommPort->labeltype(FL_NORMAL_LABEL);
      selectCommPort->labelfont(0);
      selectCommPort->labelsize(14);
      selectCommPort->labelcolor(FL_FOREGROUND_COLOR);
      selectCommPort->align(Fl_Align(FL_ALIGN_LEFT));
      selectCommPort->when(FL_WHEN_RELEASE);
      selectCommPort->end();
    } // Fl_ComboBox* selectCommPort
    { Fl_Input* o = inpXmlAddress = new Fl_Input(75, 45, 190, 23, _("Xml Addr"));
      inpXmlAddress->tooltip(_("External logbook net address"));
      inpXmlAddress->callback((Fl_Callback*)cb_inpXmlAddress);
      o->value(progStatus.log_address.c_str());
    } // Fl_Input* inpXmlAddress
    { Fl_Input* o = inpXmlPort = new Fl_Input(75, 77, 190, 23, _("Xml Port"));
      inpXmlPort->tooltip(_("External logbook net port"));
      inpXmlPort->callback((Fl_Callback*)cb_inpXmlPort);
      o->value(progStatus.log_port.c_str());
    } // Fl_Input* inpXmlPort
    { btn_ser_port_ok = new Fl_Return_Button(193, 114, 67, 20, _("OK"));
      btn_ser_port_ok->callback((Fl_Callback*)cb_btn_ser_port_ok);
    } // Fl_Return_Button* btn_ser_port_ok
    { btn_serial_port_cancel = new Fl_Button(115, 114, 70, 20, _("Cancel"));
      btn_serial_port_cancel->callback((Fl_Callback*)cb_btn_serial_port_cancel);
    } // Fl_Button* btn_serial_port_cancel
    o->end();
  } // Fl_Double_Window* o
  return w;
}

static void cb_mnu_exit(Fl_Menu_*, void*) {
  cbExit();
}

static void cb_mnu_sel_port(Fl_Menu_*, void*) {
  config_comm_port();
}

static void cb_mnu_parameters(Fl_Menu_*, void*) {
  config_parameters();
}

static void cb_mnu_messages(Fl_Menu_*, void*) {
  config_messages();
}

static void cb_mnu_operator(Fl_Menu_*, void*) {
  open_operator_dialog();
}

static void cb_mnu_display_log(Fl_Menu_*, void*) {
  cb_mnuShowLogbook();
}

static void cb_mnu_new_log(Fl_Menu_*, void*) {
  cb_mnuNewLogbook();
}

static void cb_mnu_open_logbook(Fl_Menu_*, void*) {
  cb_mnuOpenLogbook();
}

static void cb_mnu_save_logbook(Fl_Menu_*, void*) {
  cb_mnuSaveLogbook();
}

static void cb_mnu_merge_logbook(Fl_Menu_*, void*) {
  cb_mnuMergeADIF_log();
}

static void cb_mnu_export_adif(Fl_Menu_*, void*) {
  cb_mnuExportADIF_log();
}

static void cb_mnu_export_logbook_text(Fl_Menu_*, void*) {
  cb_mnuExportTEXT_log();
}

static void cb_mnu_export_logbook_csv(Fl_Menu_*, void*) {
  cb_mnuExportCSV_log();
}

static void cb_mnu_export_cabrillo(Fl_Menu_*, void*) {
  cb_Export_Cabrillo();
}

static void cb_mnu_log_client(Fl_Menu_*, void*) {
  connect_to_server();
}

static void cb_mnu_contest(Fl_Menu_*, void*) {
  cb_contest();
}

static void cb_mnu_events(Fl_Menu_*, void*) {
  cb_events();
}

static void cb_mnu_about(Fl_Menu_*, void*) {
  about();
}

static void cb_mnu_on_line_help(Fl_Menu_*, void*) {
  on_line_help();
}

unsigned char menu__i18n_done = 0;
Fl_Menu_Item menu_[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"E&xit", 0,  (Fl_Callback*)cb_mnu_exit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Configure", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Ports", 0,  (Fl_Callback*)cb_mnu_sel_port, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Parameters", 0,  (Fl_Callback*)cb_mnu_parameters, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Messages", 0,  (Fl_Callback*)cb_mnu_messages, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Operator", 0,  (Fl_Callback*)cb_mnu_operator, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Logbook", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Display Log", 0,  (Fl_Callback*)cb_mnu_display_log, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"New", 0,  (Fl_Callback*)cb_mnu_new_log, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open", 0,  (Fl_Callback*)cb_mnu_open_logbook, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save", 0,  (Fl_Callback*)cb_mnu_save_logbook, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Merge Log", 0,  (Fl_Callback*)cb_mnu_merge_logbook, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Export Log", 0,  (Fl_Callback*)cb_mnu_export_adif, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Export text", 0,  (Fl_Callback*)cb_mnu_export_logbook_text, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Export CSV", 0,  (Fl_Callback*)cb_mnu_export_logbook_csv, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Cabrillo Report", 0,  (Fl_Callback*)cb_mnu_export_cabrillo, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Connect to Server", 0,  (Fl_Callback*)cb_mnu_log_client, 0, 130, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Contest", 0,  (Fl_Callback*)cb_mnu_contest, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Events", 0,  (Fl_Callback*)cb_mnu_events, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"About", 0,  (Fl_Callback*)cb_mnu_about, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"On line help", 0,  (Fl_Callback*)cb_mnu_on_line_help, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

FTextView *txt_sent=(FTextView *)0;

FTextTX *txt_to_send=(FTextTX *)0;

Fl_Button *btn_msg1=(Fl_Button *)0;

static void cb_btn_msg1(Fl_Button*, void*) {
  exec_msg1();
}

Fl_Button *btn_msg2=(Fl_Button *)0;

static void cb_btn_msg2(Fl_Button*, void*) {
  exec_msg2();
}

Fl_Button *btn_msg3=(Fl_Button *)0;

static void cb_btn_msg3(Fl_Button*, void*) {
  exec_msg3();
}

Fl_Button *btn_msg4=(Fl_Button *)0;

static void cb_btn_msg4(Fl_Button*, void*) {
  exec_msg4();
}

Fl_Button *btn_msg5=(Fl_Button *)0;

static void cb_btn_msg5(Fl_Button*, void*) {
  exec_msg5();
}

Fl_Button *btn_msg6=(Fl_Button *)0;

static void cb_btn_msg6(Fl_Button*, void*) {
  exec_msg6();
}

Fl_Button *btn_msg7=(Fl_Button *)0;

static void cb_btn_msg7(Fl_Button*, void*) {
  exec_msg7();
}

Fl_Button *btn_msg8=(Fl_Button *)0;

static void cb_btn_msg8(Fl_Button*, void*) {
  exec_msg8();
}

Fl_Button *btn_msg9=(Fl_Button *)0;

static void cb_btn_msg9(Fl_Button*, void*) {
  exec_msg9();
}

Fl_Button *btn_msg10=(Fl_Button *)0;

static void cb_btn_msg10(Fl_Button*, void*) {
  exec_msg10();
}

Fl_Button *btn_msg11=(Fl_Button *)0;

static void cb_btn_msg11(Fl_Button*, void*) {
  exec_msg11();
}

Fl_Button *btn_msg12=(Fl_Button *)0;

static void cb_btn_msg12(Fl_Button*, void*) {
  exec_msg12();
}

Fl_Box *box_wait=(Fl_Box *)0;

Fl_Box *box_break_in=(Fl_Box *)0;

Fl_Box *box_busy=(Fl_Box *)0;

Fl_Box *box_xoff=(Fl_Box *)0;

Fl_Box *box_keydown=(Fl_Box *)0;

Fl_Check_Button *btn_use_pot=(Fl_Check_Button *)0;

static void cb_btn_use_pot(Fl_Check_Button*, void*) {
  use_pot_changed();
}

Fl_Output *txt_wpm=(Fl_Output *)0;

Fl_Counter *cntr_wpm=(Fl_Counter *)0;

static void cb_cntr_wpm(Fl_Counter*, void*) {
  set_wpm();
}

Fl_Light_Button *btn_send=(Fl_Light_Button *)0;

static void cb_btn_send(Fl_Light_Button*, void*) {
  cb_send_button();
}

Fl_Input2 *txt_sta=(Fl_Input2 *)0;

static void cb_txt_sta(Fl_Input2*, void*) {
  check_call();
}

Fl_Button *btn_time_on=(Fl_Button *)0;

static void cb_btn_time_on(Fl_Button*, void*) {
  set_time_on();
}

Fl_Input2 *txt_name=(Fl_Input2 *)0;

#ifndef NO_XML
Fl_Input2 *txt_xchg=(Fl_Input2 *)0;
#endif

Fl_Input2 *txt_time_on=(Fl_Input2 *)0;

Fl_Button *btn_clear=(Fl_Button *)0;

static void cb_btn_clear(Fl_Button*, void*) {
  txt_sta->value("");
txt_name->value("");
#ifndef NO_XML
txt_xchg->value("");
#endif
txt_sta->color(FL_BACKGROUND2_COLOR);
txt_sta->take_focus();
}

Fl_Output *txt_time_off=(Fl_Output *)0;

Fl_Button *btn_log_it=(Fl_Button *)0;

#ifndef NO_XML
static void cb_btn_log_it(Fl_Button*, void*) {
  if (mnu_log_client->value())
  xml_add_record();
else
  AddRecord();
txt_sta->take_focus();
}
#endif

Fl_Light_Button *btn_tune=(Fl_Light_Button *)0;

static void cb_btn_tune(Fl_Light_Button*, void*) {
  cb_tune();
}

Fl_Button *btn_cancel=(Fl_Button *)0;

static void cb_btn_cancel(Fl_Button*, void*) {
  cb_cancel_transmit();
}

#ifndef NO_XML
Fl_Group *xcvr_group=(Fl_Group *)0;

Fl_Round_Button *btn_vfoA=(Fl_Round_Button *)0;

static void cb_btn_vfoA(Fl_Round_Button*, void*) {
  cb_vfoAB();
}

Fl_Round_Button *btn_vfoB=(Fl_Round_Button *)0;

static void cb_btn_vfoB(Fl_Round_Button*, void*) {
  cb_vfoAB();
}

cFreqControl *xcvr_freq=(cFreqControl *)0;

static void cb_xcvr_freq(cFreqControl*, void*) {
  cb_frequency();
}

Fl_ComboBox *opMODE=(Fl_ComboBox *)0;

static void cb_opMODE(Fl_ComboBox*, void*) {
  cb_mode();
}

Fl_ComboBox *opBW1=(Fl_ComboBox *)0;

static void cb_opBW1(Fl_ComboBox*, void*) {
  cb_bw();
}

Fl_ComboBox *opBW2=(Fl_ComboBox *)0;

static void cb_opBW2(Fl_ComboBox*, void*) {
  cb_bw();
}
#endif

Fl_Button *btn_Quit=(Fl_Button *)0;

static void cb_btn_Quit(Fl_Button*, void*) {
  cbExit();
}

Fl_Double_Window* WKey_window() {
  Fl_Double_Window* w;
  int row;
#ifndef NO_XML
  { Fl_Double_Window* o = new Fl_Double_Window(670, 400, _("Fl_WinKey"));
#else
  { Fl_Double_Window* o = new Fl_Double_Window(670, 300, _("Fl_WinKey"));
#endif
    w = o;
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 670, 20);
      if (!menu__i18n_done) {
        int i=0;
        for ( ; i<26; i++)
          if (menu_[i].label())
            menu_[i].label(_(menu_[i].label()));
        menu__i18n_done = 1;
      }
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    row=27;
#ifndef NO_XML
    { xcvr_group = new Fl_Group(5, row, 662, 68, _("Xcvr"));
      row +=70;
      xcvr_group->box(FL_ENGRAVED_FRAME);
      xcvr_group->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      { Fl_Group* o = new Fl_Group(10, row+19, 60, 44);
        { btn_vfoA = new Fl_Round_Button(12, row+23, 56, 15, _("vfo A"));
          btn_vfoA->type(102);
          btn_vfoA->down_box(FL_ROUND_DOWN_BOX);
          btn_vfoA->value(1);
          btn_vfoA->callback((Fl_Callback*)cb_btn_vfoA);
        } // Fl_Round_Button* btn_vfoA
        { btn_vfoB = new Fl_Round_Button(12, row+45, 56, 15, _("vfo B"));
          btn_vfoB->type(102);
          btn_vfoB->down_box(FL_ROUND_DOWN_BOX);
          btn_vfoB->callback((Fl_Callback*)cb_btn_vfoB);
        } // Fl_Round_Button* btn_vfoB
        o->end();
      } // Fl_Group* o
      { xcvr_freq = new cFreqControl(73, row+19, 200, 44);
        xcvr_freq->box(FL_DOWN_BOX);
        xcvr_freq->color(FL_BACKGROUND_COLOR);
        xcvr_freq->selection_color(FL_BACKGROUND_COLOR);
        xcvr_freq->labeltype(FL_NORMAL_LABEL);
        xcvr_freq->labelfont(0);
        xcvr_freq->labelsize(14);
        xcvr_freq->labelcolor(FL_FOREGROUND_COLOR);
        xcvr_freq->callback((Fl_Callback*)cb_xcvr_freq);
        xcvr_freq->align(Fl_Align(FL_ALIGN_TOP));
        xcvr_freq->when(FL_WHEN_RELEASE);
        xcvr_freq->end();
      } // cFreqControl* xcvr_freq
      { opMODE = new Fl_ComboBox(284, row+19, 100, 24, _("Mode"));
        opMODE->box(FL_DOWN_BOX);
        opMODE->color(FL_BACKGROUND_COLOR);
        opMODE->selection_color(FL_BACKGROUND_COLOR);
        opMODE->labeltype(FL_NORMAL_LABEL);
        opMODE->labelfont(0);
        opMODE->labelsize(14);
        opMODE->labelcolor(FL_FOREGROUND_COLOR);
        opMODE->callback((Fl_Callback*)cb_opMODE);
        opMODE->align(Fl_Align(FL_ALIGN_TOP));
        opMODE->when(FL_WHEN_RELEASE);
        opMODE->end();
      } // Fl_ComboBox* opMODE
      { opBW1 = new Fl_ComboBox(410, row+19, 100, 24, _("Bandwidth"));
        opBW1->box(FL_DOWN_BOX);
        opBW1->color(FL_BACKGROUND_COLOR);
        opBW1->selection_color(FL_BACKGROUND_COLOR);
        opBW1->labeltype(FL_NORMAL_LABEL);
        opBW1->labelfont(0);
        opBW1->labelsize(14);
        opBW1->labelcolor(FL_FOREGROUND_COLOR);
        opBW1->callback((Fl_Callback*)cb_opBW1);
        opBW1->align(Fl_Align(FL_ALIGN_TOP));
        opBW1->when(FL_WHEN_RELEASE);
        opBW1->end();
      } // Fl_ComboBox* opBW1
      { opBW2 = new Fl_ComboBox(537, row+19, 100, 24);
        opBW2->box(FL_DOWN_BOX);
        opBW2->color(FL_BACKGROUND_COLOR);
        opBW2->selection_color(FL_BACKGROUND_COLOR);
        opBW2->labeltype(FL_NORMAL_LABEL);
        opBW2->labelfont(0);
        opBW2->labelsize(14);
        opBW2->labelcolor(FL_FOREGROUND_COLOR);
        opBW2->callback((Fl_Callback*)cb_opBW2);
        opBW2->align(Fl_Align(FL_ALIGN_TOP));
        opBW2->when(FL_WHEN_RELEASE);
        opBW2->end();
      } // Fl_ComboBox* opBW2
      xcvr_group->end();
    } // Fl_Group* xcvr_group
    row +=70;
#endif
    { txt_sent = new FTextView(8, row, 660, 65);
      txt_sent->type(12);
      txt_sent->box(FL_DOWN_BOX);
      txt_sent->color(FL_BACKGROUND2_COLOR);
      txt_sent->selection_color(FL_SELECTION_COLOR);
      txt_sent->labeltype(FL_NORMAL_LABEL);
      txt_sent->labelfont(0);
      txt_sent->labelsize(14);
      txt_sent->labelcolor(FL_FOREGROUND_COLOR);
      txt_sent->align(Fl_Align(FL_ALIGN_LEFT));
      txt_sent->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(txt_sent);
    } // FTextView* txt_sent
    row +=67;
    { txt_to_send = new FTextTX(8, row, 660, 65, _("input:")); // second text bos from 85 to 135
      txt_to_send->type(4);
      txt_to_send->box(FL_DOWN_BOX);
      txt_to_send->color(FL_BACKGROUND2_COLOR);
      txt_to_send->selection_color(FL_SELECTION_COLOR);
      txt_to_send->labeltype(FL_NORMAL_LABEL);
      txt_to_send->labelfont(0);
      txt_to_send->labelsize(14);
      txt_to_send->labelcolor(FL_FOREGROUND_COLOR);
      txt_to_send->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      txt_to_send->when(FL_WHEN_CHANGED);
    } // FTextTX* txt_to_send
    row +=67;
    { btn_msg1 = new Fl_Button(7, row, 50, 24, _("m 1"));
      btn_msg1->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg1->callback((Fl_Callback*)cb_btn_msg1);
    } // Fl_Button* btn_msg1
    { btn_msg2 = new Fl_Button(62, row, 50, 24, _("m 2"));
      btn_msg2->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg2->callback((Fl_Callback*)cb_btn_msg2);
    } // Fl_Button* btn_msg2
    { btn_msg3 = new Fl_Button(118, row, 50, 24, _("m 3"));
      btn_msg3->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg3->callback((Fl_Callback*)cb_btn_msg3);
    } // Fl_Button* btn_msg3
    { btn_msg4 = new Fl_Button(173, row, 50, 24, _("m 4"));
      btn_msg4->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg4->callback((Fl_Callback*)cb_btn_msg4);
    } // Fl_Button* btn_msg4
    { btn_msg5 = new Fl_Button(229, row, 50, 24, _("m 5"));
      btn_msg5->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg5->callback((Fl_Callback*)cb_btn_msg5);
    } // Fl_Button* btn_msg5
    { btn_msg6 = new Fl_Button(284, row, 50, 24, _("m 6"));
      btn_msg6->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg6->callback((Fl_Callback*)cb_btn_msg6);
    } // Fl_Button* btn_msg6
    { btn_msg7 = new Fl_Button(340, row, 50, 24, _("m 7"));
      btn_msg7->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg7->callback((Fl_Callback*)cb_btn_msg7);
    } // Fl_Button* btn_msg7
    { btn_msg8 = new Fl_Button(395, row, 50, 24, _("m 8"));
      btn_msg8->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg8->callback((Fl_Callback*)cb_btn_msg8);
    } // Fl_Button* btn_msg8
    { btn_msg9 = new Fl_Button(451, row, 50, 24, _("m 9"));
      btn_msg9->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg9->callback((Fl_Callback*)cb_btn_msg9);
    } // Fl_Button* btn_msg9
    { btn_msg10 = new Fl_Button(506, row, 50, 24, _("m 10"));
      btn_msg10->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg10->callback((Fl_Callback*)cb_btn_msg10);
    } // Fl_Button* btn_msg10
    { btn_msg11 = new Fl_Button(562, row, 50, 24, _("m 11"));
      btn_msg11->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg11->callback((Fl_Callback*)cb_btn_msg11);
    } // Fl_Button* btn_msg11
    { btn_msg12 = new Fl_Button(618, row, 50, 24, _("m 12"));
      btn_msg12->tooltip(_("Action - Fkey/Left click\nEdit - Right click"));
      btn_msg12->callback((Fl_Callback*)cb_btn_msg12);
    } // Fl_Button* btn_msg12
    row +=35;
    { box_wait = new Fl_Box(10, row, 16, 16, _("Wait"));
      box_wait->box(FL_DIAMOND_DOWN_BOX);
      box_wait->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Box* box_wait
    { box_break_in = new Fl_Box(85, row, 16, 16, _("Bk"));
      box_break_in->box(FL_DIAMOND_DOWN_BOX);
      box_break_in->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Box* box_break_in
    { box_busy = new Fl_Box(160, row, 16, 16, _("Busy"));
      box_busy->box(FL_DIAMOND_DOWN_BOX);
      box_busy->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Box* box_busy
    { box_xoff = new Fl_Box(235, row, 16, 16, _("Bfr"));
      box_xoff->box(FL_DIAMOND_DOWN_BOX);
      box_xoff->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Box* box_xoff
    { box_keydown = new Fl_Box(311, row, 16, 16, _("Key"));
      box_keydown->box(FL_DIAMOND_DOWN_BOX);
      box_keydown->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Box* box_keydown
    { btn_use_pot = new Fl_Check_Button(400, row, 20, 15, _("Pot"));
      btn_use_pot->tooltip(_("Winkeyer pot controls WPM"));
      btn_use_pot->down_box(FL_DOWN_BOX);
      btn_use_pot->callback((Fl_Callback*)cb_btn_use_pot);
      btn_use_pot->align(Fl_Align(FL_ALIGN_LEFT));
      btn_use_pot->when(FL_WHEN_CHANGED);
    } // Fl_Check_Button* btn_use_pot
    { txt_wpm = new Fl_Output(428, row-5, 50, 24);
    } // Fl_Output* txt_wpm
    { Fl_Counter* o = cntr_wpm = new Fl_Counter(528, row-5, 64, 24, _("WPM"));
      cntr_wpm->tooltip(_("flwkey WPM"));
      cntr_wpm->type(1);
      cntr_wpm->minimum(10);
      cntr_wpm->maximum(35);
      cntr_wpm->step(1);
      cntr_wpm->value(20);
      cntr_wpm->callback((Fl_Callback*)cb_cntr_wpm);
      cntr_wpm->align(Fl_Align(FL_ALIGN_LEFT));
      o->value(progStatus.speed_wpm);
    } // Fl_Counter* cntr_wpm
    { btn_send = new Fl_Light_Button(608, row-5, 60, 24, _("Send"));
      btn_send->callback((Fl_Callback*)cb_btn_send);
    } // Fl_Light_Button* btn_send
    row +=30;
    { Fl_Group* o = new Fl_Group(5, row-5, 484, 68);
      o->box(FL_ENGRAVED_BOX);
      { txt_sta = new Fl_Input2(48, row, 120, 24, _("STA"));
        txt_sta->tooltip(_("Other station"));
        txt_sta->box(FL_DOWN_BOX);
        txt_sta->color(FL_BACKGROUND2_COLOR);
        txt_sta->selection_color(FL_SELECTION_COLOR);
        txt_sta->labeltype(FL_NORMAL_LABEL);
        txt_sta->labelfont(0);
        txt_sta->labelsize(14);
        txt_sta->labelcolor(FL_FOREGROUND_COLOR);
        txt_sta->callback((Fl_Callback*)cb_txt_sta);
        txt_sta->align(Fl_Align(FL_ALIGN_LEFT));
        txt_sta->when(FL_WHEN_CHANGED);
      } // Fl_Input2* txt_sta
      { btn_time_on = new Fl_Button(178, row, 32, 24, _("On:"));
        btn_time_on->tooltip(_("Press to set time on"));
        btn_time_on->down_box(FL_DOWN_BOX);
        btn_time_on->color((Fl_Color)48);
        btn_time_on->callback((Fl_Callback*)cb_btn_time_on);
      } // Fl_Button* btn_time_on
      { txt_name = new Fl_Input2(48, row+30, 120, 24, _("NAM"));
        txt_name->tooltip(_("Other operator"));
        txt_name->box(FL_DOWN_BOX);
        txt_name->color(FL_BACKGROUND2_COLOR);
        txt_name->selection_color(FL_SELECTION_COLOR);
        txt_name->labeltype(FL_NORMAL_LABEL);
        txt_name->labelfont(0);
        txt_name->labelsize(14);
        txt_name->labelcolor(FL_FOREGROUND_COLOR);
        txt_name->align(Fl_Align(FL_ALIGN_LEFT));
        txt_name->when(FL_WHEN_RELEASE);
      } // Fl_Input2* txt_name
#ifndef NO_XML
      { txt_xchg = new Fl_Input2(211, row+30, 200, 24, _("X_in"));
        txt_xchg->tooltip(_("Rcvd Contest Exchange"));
        txt_xchg->box(FL_DOWN_BOX);
        txt_xchg->color(FL_BACKGROUND2_COLOR);
        txt_xchg->selection_color(FL_SELECTION_COLOR);
        txt_xchg->labeltype(FL_NORMAL_LABEL);
        txt_xchg->labelfont(0);
        txt_xchg->labelsize(14);
        txt_xchg->labelcolor(FL_FOREGROUND_COLOR);
        txt_xchg->align(Fl_Align(FL_ALIGN_LEFT));
        txt_xchg->when(FL_WHEN_CHANGED);
      } // Fl_Input2* txt_xchg
#endif
      { txt_time_on = new Fl_Input2(211, row, 80, 24);
        txt_time_on->tooltip(_("Frequency (MHz preferred)"));
        txt_time_on->box(FL_DOWN_BOX);
        txt_time_on->color(FL_BACKGROUND2_COLOR);
        txt_time_on->selection_color(FL_SELECTION_COLOR);
        txt_time_on->labeltype(FL_NORMAL_LABEL);
        txt_time_on->labelfont(0);
        txt_time_on->labelsize(14);
        txt_time_on->labelcolor(FL_FOREGROUND_COLOR);
        txt_time_on->align(Fl_Align(FL_ALIGN_LEFT));
        txt_time_on->when(FL_WHEN_CHANGED);
      } // Fl_Input2* txt_time_on
      { btn_clear = new Fl_Button(428, row, 52, 24, _("Clear"));
        btn_clear->callback((Fl_Callback*)cb_btn_clear);
      } // Fl_Button* btn_clear
      { txt_time_off = new Fl_Output(331, row, 80, 24, _("Off:"));
        txt_time_off->tooltip(_("time off"));
      } // Fl_Output* txt_time_off
#ifndef NO_XML
      { btn_log_it = new Fl_Button(428, row+30, 52, 24, _("Log"));
        btn_log_it->callback((Fl_Callback*)cb_btn_log_it);
      } // Fl_Button* btn_log_it
#endif
      o->end();
    } // Fl_Group* o
    { btn_tune = new Fl_Light_Button(530, row, 60, 24, _("Tune"));
      btn_tune->selection_color((Fl_Color)5);
      btn_tune->callback((Fl_Callback*)cb_btn_tune);
    } // Fl_Light_Button* btn_tune
    { btn_cancel = new Fl_Button(608, row, 60, 24, _("Cancel"));
      btn_cancel->callback((Fl_Callback*)cb_btn_cancel);
    } // Fl_Button* btn_cancel
    { btn_Quit = new Fl_Button(608, row+30, 60, 24, _("Quit"));
      btn_Quit->callback((Fl_Callback*)cb_btn_Quit);
    } // Fl_Button* btn_Quit
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Check_Button *btn_swap=(Fl_Check_Button *)0;

static void cb_btn_swap(Fl_Check_Button*, void*) {
  change_btn_swap();
}

Fl_Check_Button *btn_auto_space=(Fl_Check_Button *)0;

static void cb_btn_auto_space(Fl_Check_Button*, void*) {
  change_btn_auto_space();
}

Fl_Check_Button *btn_ct_space=(Fl_Check_Button *)0;

static void cb_btn_ct_space(Fl_Check_Button*, void*) {
  change_btn_ct_space();
}

Fl_Check_Button *btn_paddledog=(Fl_Check_Button *)0;

static void cb_btn_paddledog(Fl_Check_Button*, void*) {
  change_btn_paddledog();
}

Fl_Check_Button *btn_cut_zeronine=(Fl_Check_Button *)0;

static void cb_btn_cut_zeronine(Fl_Check_Button*, void*) {
  change_btn_cut_zeronine();
}

Fl_Check_Button *btn_paddle_echo=(Fl_Check_Button *)0;

static void cb_btn_paddle_echo(Fl_Check_Button*, void*) {
  change_btn_paddle_echo();
}

Fl_Check_Button *btn_serial_echo=(Fl_Check_Button *)0;

static void cb_btn_serial_echo(Fl_Check_Button*, void*) {
  change_btn_serial_echo();
}

Fl_Check_Button *btn_sidetone_on=(Fl_Check_Button *)0;

static void cb_btn_sidetone_on(Fl_Check_Button*, void*) {
  change_btn_sidetone_on();
}

Fl_Check_Button *btn_tone_on=(Fl_Check_Button *)0;

static void cb_btn_tone_on(Fl_Check_Button*, void*) {
  change_btn_tone_on();
}

Fl_Check_Button *btn_ptt_on=(Fl_Check_Button *)0;

static void cb_btn_ptt_on(Fl_Check_Button*, void*) {
  change_btn_ptt_on();
}

Fl_Counter *cntr_min_wpm=(Fl_Counter *)0;

static void cb_cntr_min_wpm(Fl_Counter*, void*) {
  change_cntr_min_wpm();
}

Fl_Counter *cntr_rng_wpm=(Fl_Counter *)0;

static void cb_cntr_rng_wpm(Fl_Counter*, void*) {
  change_cntr_rng_wpm();
}

Fl_Counter *cntr_farnsworth=(Fl_Counter *)0;

static void cb_cntr_farnsworth(Fl_Counter*, void*) {
  change_cntr_farnsworth();
}

Fl_Counter *cntr_cmd_wpm=(Fl_Counter *)0;

static void cb_cntr_cmd_wpm(Fl_Counter*, void*) {
  change_cntr_cmd_wpm();
}

Fl_Counter *cntr_ratio=(Fl_Counter *)0;

static void cb_cntr_ratio(Fl_Counter*, void*) {
  change_cntr_ratio();
}

Fl_Counter *cntr_comp=(Fl_Counter *)0;

static void cb_cntr_comp(Fl_Counter*, void*) {
  change_cntr_comp();
}

Fl_Counter *cntr_first_ext=(Fl_Counter *)0;

static void cb_cntr_first_ext(Fl_Counter*, void*) {
  change_cntr_first_ext();
}

Fl_Counter *cntr_sample=(Fl_Counter *)0;

static void cb_cntr_sample(Fl_Counter*, void*) {
  change_cntr_sample();
}

Fl_Counter *cntr_weight=(Fl_Counter *)0;

static void cb_cntr_weight(Fl_Counter*, void*) {
  change_cntr_weight();
}

Fl_Counter *cntr_leadin=(Fl_Counter *)0;

static void cb_cntr_leadin(Fl_Counter*, void*) {
  change_cntr_leadin();
}

Fl_Counter *cntr_tail=(Fl_Counter *)0;

static void cb_cntr_tail(Fl_Counter*, void*) {
  change_cntr_tail();
}

Fl_ComboBox *choice_keyer_mode=(Fl_ComboBox *)0;

static void cb_choice_keyer_mode(Fl_ComboBox*, void*) {
  change_choice_keyer_mode();
}

Fl_ComboBox *choice_hang=(Fl_ComboBox *)0;

static void cb_choice_hang(Fl_ComboBox*, void*) {
  change_choice_hang();
}

Fl_ComboBox *choice_sidetone=(Fl_ComboBox *)0;

static void cb_choice_sidetone(Fl_ComboBox*, void*) {
  change_choice_sidetone();
}

Fl_ComboBox *choice_output_pins=(Fl_ComboBox *)0;

static void cb_choice_output_pins(Fl_ComboBox*, void*) {
  change_choice_output_pins();
}

Fl_Button *btn_done_parameters=(Fl_Button *)0;

static void cb_btn_done_parameters(Fl_Button*, void*) {
  done_parameters();
}

Fl_Double_Window* make_parameters_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(515, 232, _("WKeyer Parameters"));
    w = o;
    { Fl_Group* o = new Fl_Group(5, 23, 115, 114, _("ModeReg"));
      o->box(FL_ENGRAVED_FRAME);
      { btn_swap = new Fl_Check_Button(15, 31, 70, 15, _("Swap"));
        btn_swap->down_box(FL_DOWN_BOX);
        btn_swap->callback((Fl_Callback*)cb_btn_swap);
      } // Fl_Check_Button* btn_swap
      { btn_auto_space = new Fl_Check_Button(15, 51, 70, 15, _("Auto Space"));
        btn_auto_space->down_box(FL_DOWN_BOX);
        btn_auto_space->callback((Fl_Callback*)cb_btn_auto_space);
      } // Fl_Check_Button* btn_auto_space
      { btn_ct_space = new Fl_Check_Button(15, 72, 70, 15, _("CT space"));
        btn_ct_space->down_box(FL_DOWN_BOX);
        btn_ct_space->callback((Fl_Callback*)cb_btn_ct_space);
      } // Fl_Check_Button* btn_ct_space
      { btn_paddledog = new Fl_Check_Button(15, 92, 70, 15, _("Paddle Dog"));
        btn_paddledog->down_box(FL_DOWN_BOX);
        btn_paddledog->callback((Fl_Callback*)cb_btn_paddledog);
      } // Fl_Check_Button* btn_paddledog
      { btn_cut_zeronine = new Fl_Check_Button(15, 113, 70, 15, _("Cut 0/9"));
        btn_cut_zeronine->down_box(FL_DOWN_BOX);
        btn_cut_zeronine->callback((Fl_Callback*)cb_btn_cut_zeronine);
      } // Fl_Check_Button* btn_cut_zeronine
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(122, 23, 115, 114, _("ModeReg"));
      o->box(FL_ENGRAVED_FRAME);
      { btn_paddle_echo = new Fl_Check_Button(128, 31, 70, 15, _("Paddle echo"));
        btn_paddle_echo->down_box(FL_DOWN_BOX);
        btn_paddle_echo->callback((Fl_Callback*)cb_btn_paddle_echo);
      } // Fl_Check_Button* btn_paddle_echo
      { btn_serial_echo = new Fl_Check_Button(128, 51, 70, 15, _("Serial echo"));
        btn_serial_echo->down_box(FL_DOWN_BOX);
        btn_serial_echo->callback((Fl_Callback*)cb_btn_serial_echo);
      } // Fl_Check_Button* btn_serial_echo
      { btn_sidetone_on = new Fl_Check_Button(128, 71, 103, 15, _("Tone Keyer"));
        btn_sidetone_on->down_box(FL_DOWN_BOX);
        btn_sidetone_on->callback((Fl_Callback*)cb_btn_sidetone_on);
      } // Fl_Check_Button* btn_sidetone_on
      { btn_tone_on = new Fl_Check_Button(128, 92, 87, 15, _("Tone ON"));
        btn_tone_on->down_box(FL_DOWN_BOX);
        btn_tone_on->callback((Fl_Callback*)cb_btn_tone_on);
      } // Fl_Check_Button* btn_tone_on
      { btn_ptt_on = new Fl_Check_Button(128, 113, 87, 15, _("PTT ON"));
        btn_ptt_on->down_box(FL_DOWN_BOX);
        btn_ptt_on->callback((Fl_Callback*)cb_btn_ptt_on);
      } // Fl_Check_Button* btn_ptt_on
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(240, 23, 112, 165, _("WPM Settings"));
      o->box(FL_ENGRAVED_FRAME);
      { cntr_min_wpm = new Fl_Counter(261, 31, 64, 20, _("Min WPM"));
        cntr_min_wpm->type(1);
        cntr_min_wpm->callback((Fl_Callback*)cb_cntr_min_wpm);
      } // Fl_Counter* cntr_min_wpm
      { cntr_rng_wpm = new Fl_Counter(261, 68, 64, 20, _("Rng WPM"));
        cntr_rng_wpm->type(1);
        cntr_rng_wpm->callback((Fl_Callback*)cb_cntr_rng_wpm);
      } // Fl_Counter* cntr_rng_wpm
      { cntr_farnsworth = new Fl_Counter(261, 105, 64, 20, _("Farsnworth"));
        cntr_farnsworth->type(1);
        cntr_farnsworth->callback((Fl_Callback*)cb_cntr_farnsworth);
      } // Fl_Counter* cntr_farnsworth
      { cntr_cmd_wpm = new Fl_Counter(261, 143, 64, 20, _("Cmd WPM"));
        cntr_cmd_wpm->type(1);
        cntr_cmd_wpm->callback((Fl_Callback*)cb_cntr_cmd_wpm);
      } // Fl_Counter* cntr_cmd_wpm
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(353, 23, 159, 165, _("Timing/Settings"));
      o->box(FL_ENGRAVED_FRAME);
      { cntr_ratio = new Fl_Counter(365, 31, 64, 20, _("Ratio"));
        cntr_ratio->type(1);
        cntr_ratio->callback((Fl_Callback*)cb_cntr_ratio);
      } // Fl_Counter* cntr_ratio
      { cntr_comp = new Fl_Counter(365, 68, 64, 20, _("Comp"));
        cntr_comp->type(1);
        cntr_comp->callback((Fl_Callback*)cb_cntr_comp);
      } // Fl_Counter* cntr_comp
      { cntr_first_ext = new Fl_Counter(365, 105, 64, 20, _("1st Ext"));
        cntr_first_ext->type(1);
        cntr_first_ext->callback((Fl_Callback*)cb_cntr_first_ext);
      } // Fl_Counter* cntr_first_ext
      { cntr_sample = new Fl_Counter(365, 143, 64, 20, _("Sample"));
        cntr_sample->type(1);
        cntr_sample->callback((Fl_Callback*)cb_cntr_sample);
      } // Fl_Counter* cntr_sample
      { cntr_weight = new Fl_Counter(436, 31, 64, 20, _("Weight"));
        cntr_weight->type(1);
        cntr_weight->callback((Fl_Callback*)cb_cntr_weight);
      } // Fl_Counter* cntr_weight
      { cntr_leadin = new Fl_Counter(436, 68, 64, 20, _("Leadin"));
        cntr_leadin->type(1);
        cntr_leadin->callback((Fl_Callback*)cb_cntr_leadin);
      } // Fl_Counter* cntr_leadin
      { cntr_tail = new Fl_Counter(436, 105, 64, 20, _("Tail"));
        cntr_tail->type(1);
        cntr_tail->callback((Fl_Callback*)cb_cntr_tail);
      } // Fl_Counter* cntr_tail
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(5, 138, 232, 90);
      o->box(FL_ENGRAVED_FRAME);
      { choice_keyer_mode = new Fl_ComboBox(20, 143, 90, 22, _("Keyer Mode"));
        choice_keyer_mode->box(FL_BORDER_BOX);
        choice_keyer_mode->color(FL_BACKGROUND_COLOR);
        choice_keyer_mode->selection_color(FL_BACKGROUND_COLOR);
        choice_keyer_mode->labeltype(FL_NORMAL_LABEL);
        choice_keyer_mode->labelfont(0);
        choice_keyer_mode->labelsize(14);
        choice_keyer_mode->labelcolor(FL_FOREGROUND_COLOR);
        choice_keyer_mode->callback((Fl_Callback*)cb_choice_keyer_mode);
        choice_keyer_mode->align(Fl_Align(FL_ALIGN_BOTTOM));
        choice_keyer_mode->when(FL_WHEN_RELEASE);
        choice_keyer_mode->end();
      } // Fl_ComboBox* choice_keyer_mode
      { choice_hang = new Fl_ComboBox(130, 143, 90, 22, _("Hang"));
        choice_hang->box(FL_BORDER_BOX);
        choice_hang->color(FL_BACKGROUND_COLOR);
        choice_hang->selection_color(FL_BACKGROUND_COLOR);
        choice_hang->labeltype(FL_NORMAL_LABEL);
        choice_hang->labelfont(0);
        choice_hang->labelsize(14);
        choice_hang->labelcolor(FL_FOREGROUND_COLOR);
        choice_hang->callback((Fl_Callback*)cb_choice_hang);
        choice_hang->align(Fl_Align(FL_ALIGN_BOTTOM));
        choice_hang->when(FL_WHEN_RELEASE);
        choice_hang->end();
      } // Fl_ComboBox* choice_hang
      { choice_sidetone = new Fl_ComboBox(20, 185, 90, 22, _("Sidetone"));
        choice_sidetone->box(FL_BORDER_BOX);
        choice_sidetone->color(FL_BACKGROUND_COLOR);
        choice_sidetone->selection_color(FL_BACKGROUND_COLOR);
        choice_sidetone->labeltype(FL_NORMAL_LABEL);
        choice_sidetone->labelfont(0);
        choice_sidetone->labelsize(14);
        choice_sidetone->labelcolor(FL_FOREGROUND_COLOR);
        choice_sidetone->callback((Fl_Callback*)cb_choice_sidetone);
        choice_sidetone->align(Fl_Align(FL_ALIGN_BOTTOM));
        choice_sidetone->when(FL_WHEN_RELEASE);
        choice_sidetone->end();
      } // Fl_ComboBox* choice_sidetone
      { choice_output_pins = new Fl_ComboBox(130, 185, 90, 22, _("Output PIns"));
        choice_output_pins->box(FL_BORDER_BOX);
        choice_output_pins->color(FL_BACKGROUND_COLOR);
        choice_output_pins->selection_color(FL_BACKGROUND_COLOR);
        choice_output_pins->labeltype(FL_NORMAL_LABEL);
        choice_output_pins->labelfont(0);
        choice_output_pins->labelsize(14);
        choice_output_pins->labelcolor(FL_FOREGROUND_COLOR);
        choice_output_pins->callback((Fl_Callback*)cb_choice_output_pins);
        choice_output_pins->align(Fl_Align(FL_ALIGN_BOTTOM));
        choice_output_pins->when(FL_WHEN_RELEASE);
        choice_output_pins->end();
      } // Fl_ComboBox* choice_output_pins
      o->end();
    } // Fl_Group* o
    { btn_done_parameters = new Fl_Button(411, 194, 75, 27, _("Done"));
      btn_done_parameters->callback((Fl_Callback*)cb_btn_done_parameters);
    } // Fl_Button* btn_done_parameters
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Input2 *label_1=(Fl_Input2 *)0;

Fl_Input2 *edit_msg1=(Fl_Input2 *)0;

Fl_Input2 *label_2=(Fl_Input2 *)0;

Fl_Input2 *edit_msg2=(Fl_Input2 *)0;

Fl_Input2 *label_3=(Fl_Input2 *)0;

Fl_Input2 *edit_msg3=(Fl_Input2 *)0;

Fl_Input2 *label_4=(Fl_Input2 *)0;

Fl_Input2 *edit_msg4=(Fl_Input2 *)0;

Fl_Input2 *label_5=(Fl_Input2 *)0;

Fl_Input2 *edit_msg5=(Fl_Input2 *)0;

Fl_Input2 *label_6=(Fl_Input2 *)0;

Fl_Input2 *edit_msg6=(Fl_Input2 *)0;

Fl_Input2 *label_7=(Fl_Input2 *)0;

Fl_Input2 *edit_msg7=(Fl_Input2 *)0;

Fl_Input2 *label_8=(Fl_Input2 *)0;

Fl_Input2 *edit_msg8=(Fl_Input2 *)0;

Fl_Input2 *label_9=(Fl_Input2 *)0;

Fl_Input2 *edit_msg9=(Fl_Input2 *)0;

Fl_Input2 *label_10=(Fl_Input2 *)0;

Fl_Input2 *edit_msg10=(Fl_Input2 *)0;

Fl_Button *btn_done_edit=(Fl_Button *)0;

static void cb_btn_done_edit(Fl_Button*, void*) {
  done_edit();
}

Fl_Button *btn_cancel_edit=(Fl_Button *)0;

static void cb_btn_cancel_edit(Fl_Button*, void*) {
  cancel_edit();
}

Fl_Button *btn_apply_edit=(Fl_Button *)0;

static void cb_btn_apply_edit(Fl_Button*, void*) {
  apply_edit();
}

Fl_Input2 *label_11=(Fl_Input2 *)0;

Fl_Input2 *edit_msg11=(Fl_Input2 *)0;

Fl_Input2 *label_12=(Fl_Input2 *)0;

Fl_Input2 *edit_msg12=(Fl_Input2 *)0;

Fl_Double_Window* make_message_editor() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(600, 350, _("Message Editor"));
    w = o;
    { label_1 = new Fl_Input2(30, 31, 50, 22, _("1:"));
      label_1->box(FL_DOWN_BOX);
      label_1->color(FL_BACKGROUND2_COLOR);
      label_1->selection_color(FL_SELECTION_COLOR);
      label_1->labeltype(FL_NORMAL_LABEL);
      label_1->labelfont(0);
      label_1->labelsize(14);
      label_1->labelcolor(FL_FOREGROUND_COLOR);
      label_1->align(Fl_Align(FL_ALIGN_LEFT));
      label_1->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_1
    { edit_msg1 = new Fl_Input2(85, 31, 375, 22);
      edit_msg1->box(FL_DOWN_BOX);
      edit_msg1->color(FL_BACKGROUND2_COLOR);
      edit_msg1->selection_color(FL_SELECTION_COLOR);
      edit_msg1->labeltype(FL_NORMAL_LABEL);
      edit_msg1->labelfont(0);
      edit_msg1->labelsize(14);
      edit_msg1->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg1->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg1->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg1
    { label_2 = new Fl_Input2(30, 57, 50, 22, _("2:"));
      label_2->box(FL_DOWN_BOX);
      label_2->color(FL_BACKGROUND2_COLOR);
      label_2->selection_color(FL_SELECTION_COLOR);
      label_2->labeltype(FL_NORMAL_LABEL);
      label_2->labelfont(0);
      label_2->labelsize(14);
      label_2->labelcolor(FL_FOREGROUND_COLOR);
      label_2->align(Fl_Align(FL_ALIGN_LEFT));
      label_2->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_2
    { edit_msg2 = new Fl_Input2(85, 57, 375, 22);
      edit_msg2->box(FL_DOWN_BOX);
      edit_msg2->color(FL_BACKGROUND2_COLOR);
      edit_msg2->selection_color(FL_SELECTION_COLOR);
      edit_msg2->labeltype(FL_NORMAL_LABEL);
      edit_msg2->labelfont(0);
      edit_msg2->labelsize(14);
      edit_msg2->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg2->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg2->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg2
    { label_3 = new Fl_Input2(30, 83, 50, 22, _("3:"));
      label_3->box(FL_DOWN_BOX);
      label_3->color(FL_BACKGROUND2_COLOR);
      label_3->selection_color(FL_SELECTION_COLOR);
      label_3->labeltype(FL_NORMAL_LABEL);
      label_3->labelfont(0);
      label_3->labelsize(14);
      label_3->labelcolor(FL_FOREGROUND_COLOR);
      label_3->align(Fl_Align(FL_ALIGN_LEFT));
      label_3->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_3
    { edit_msg3 = new Fl_Input2(85, 83, 375, 22);
      edit_msg3->box(FL_DOWN_BOX);
      edit_msg3->color(FL_BACKGROUND2_COLOR);
      edit_msg3->selection_color(FL_SELECTION_COLOR);
      edit_msg3->labeltype(FL_NORMAL_LABEL);
      edit_msg3->labelfont(0);
      edit_msg3->labelsize(14);
      edit_msg3->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg3->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg3->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg3
    { label_4 = new Fl_Input2(30, 110, 50, 22, _("4:"));
      label_4->box(FL_DOWN_BOX);
      label_4->color(FL_BACKGROUND2_COLOR);
      label_4->selection_color(FL_SELECTION_COLOR);
      label_4->labeltype(FL_NORMAL_LABEL);
      label_4->labelfont(0);
      label_4->labelsize(14);
      label_4->labelcolor(FL_FOREGROUND_COLOR);
      label_4->align(Fl_Align(FL_ALIGN_LEFT));
      label_4->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_4
    { edit_msg4 = new Fl_Input2(85, 110, 375, 22);
      edit_msg4->box(FL_DOWN_BOX);
      edit_msg4->color(FL_BACKGROUND2_COLOR);
      edit_msg4->selection_color(FL_SELECTION_COLOR);
      edit_msg4->labeltype(FL_NORMAL_LABEL);
      edit_msg4->labelfont(0);
      edit_msg4->labelsize(14);
      edit_msg4->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg4->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg4->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg4
    { label_5 = new Fl_Input2(30, 136, 50, 22, _("5:"));
      label_5->box(FL_DOWN_BOX);
      label_5->color(FL_BACKGROUND2_COLOR);
      label_5->selection_color(FL_SELECTION_COLOR);
      label_5->labeltype(FL_NORMAL_LABEL);
      label_5->labelfont(0);
      label_5->labelsize(14);
      label_5->labelcolor(FL_FOREGROUND_COLOR);
      label_5->align(Fl_Align(FL_ALIGN_LEFT));
      label_5->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_5
    { edit_msg5 = new Fl_Input2(85, 136, 375, 22);
      edit_msg5->box(FL_DOWN_BOX);
      edit_msg5->color(FL_BACKGROUND2_COLOR);
      edit_msg5->selection_color(FL_SELECTION_COLOR);
      edit_msg5->labeltype(FL_NORMAL_LABEL);
      edit_msg5->labelfont(0);
      edit_msg5->labelsize(14);
      edit_msg5->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg5->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg5->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg5
    { label_6 = new Fl_Input2(30, 162, 50, 22, _("6:"));
      label_6->box(FL_DOWN_BOX);
      label_6->color(FL_BACKGROUND2_COLOR);
      label_6->selection_color(FL_SELECTION_COLOR);
      label_6->labeltype(FL_NORMAL_LABEL);
      label_6->labelfont(0);
      label_6->labelsize(14);
      label_6->labelcolor(FL_FOREGROUND_COLOR);
      label_6->align(Fl_Align(FL_ALIGN_LEFT));
      label_6->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_6
    { edit_msg6 = new Fl_Input2(85, 162, 375, 22);
      edit_msg6->box(FL_DOWN_BOX);
      edit_msg6->color(FL_BACKGROUND2_COLOR);
      edit_msg6->selection_color(FL_SELECTION_COLOR);
      edit_msg6->labeltype(FL_NORMAL_LABEL);
      edit_msg6->labelfont(0);
      edit_msg6->labelsize(14);
      edit_msg6->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg6->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg6->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg6
    { label_7 = new Fl_Input2(30, 189, 50, 22, _("7:"));
      label_7->box(FL_DOWN_BOX);
      label_7->color(FL_BACKGROUND2_COLOR);
      label_7->selection_color(FL_SELECTION_COLOR);
      label_7->labeltype(FL_NORMAL_LABEL);
      label_7->labelfont(0);
      label_7->labelsize(14);
      label_7->labelcolor(FL_FOREGROUND_COLOR);
      label_7->align(Fl_Align(FL_ALIGN_LEFT));
      label_7->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_7
    { edit_msg7 = new Fl_Input2(85, 189, 375, 22);
      edit_msg7->box(FL_DOWN_BOX);
      edit_msg7->color(FL_BACKGROUND2_COLOR);
      edit_msg7->selection_color(FL_SELECTION_COLOR);
      edit_msg7->labeltype(FL_NORMAL_LABEL);
      edit_msg7->labelfont(0);
      edit_msg7->labelsize(14);
      edit_msg7->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg7->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg7->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg7
    { label_8 = new Fl_Input2(30, 215, 50, 22, _("8:"));
      label_8->box(FL_DOWN_BOX);
      label_8->color(FL_BACKGROUND2_COLOR);
      label_8->selection_color(FL_SELECTION_COLOR);
      label_8->labeltype(FL_NORMAL_LABEL);
      label_8->labelfont(0);
      label_8->labelsize(14);
      label_8->labelcolor(FL_FOREGROUND_COLOR);
      label_8->align(Fl_Align(FL_ALIGN_LEFT));
      label_8->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_8
    { edit_msg8 = new Fl_Input2(85, 215, 375, 22);
      edit_msg8->box(FL_DOWN_BOX);
      edit_msg8->color(FL_BACKGROUND2_COLOR);
      edit_msg8->selection_color(FL_SELECTION_COLOR);
      edit_msg8->labeltype(FL_NORMAL_LABEL);
      edit_msg8->labelfont(0);
      edit_msg8->labelsize(14);
      edit_msg8->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg8->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg8->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg8
    { label_9 = new Fl_Input2(30, 241, 50, 22, _("9:"));
      label_9->box(FL_DOWN_BOX);
      label_9->color(FL_BACKGROUND2_COLOR);
      label_9->selection_color(FL_SELECTION_COLOR);
      label_9->labeltype(FL_NORMAL_LABEL);
      label_9->labelfont(0);
      label_9->labelsize(14);
      label_9->labelcolor(FL_FOREGROUND_COLOR);
      label_9->align(Fl_Align(FL_ALIGN_LEFT));
      label_9->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_9
    { edit_msg9 = new Fl_Input2(85, 241, 375, 22);
      edit_msg9->box(FL_DOWN_BOX);
      edit_msg9->color(FL_BACKGROUND2_COLOR);
      edit_msg9->selection_color(FL_SELECTION_COLOR);
      edit_msg9->labeltype(FL_NORMAL_LABEL);
      edit_msg9->labelfont(0);
      edit_msg9->labelsize(14);
      edit_msg9->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg9->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg9->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg9
    { label_10 = new Fl_Input2(30, 268, 50, 22, _("10:"));
      label_10->box(FL_DOWN_BOX);
      label_10->color(FL_BACKGROUND2_COLOR);
      label_10->selection_color(FL_SELECTION_COLOR);
      label_10->labeltype(FL_NORMAL_LABEL);
      label_10->labelfont(0);
      label_10->labelsize(14);
      label_10->labelcolor(FL_FOREGROUND_COLOR);
      label_10->align(Fl_Align(FL_ALIGN_LEFT));
      label_10->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_10
    { edit_msg10 = new Fl_Input2(85, 268, 375, 22);
      edit_msg10->box(FL_DOWN_BOX);
      edit_msg10->color(FL_BACKGROUND2_COLOR);
      edit_msg10->selection_color(FL_SELECTION_COLOR);
      edit_msg10->labeltype(FL_NORMAL_LABEL);
      edit_msg10->labelfont(0);
      edit_msg10->labelsize(14);
      edit_msg10->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg10->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg10->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg10
    { btn_done_edit = new Fl_Button(535, 305, 56, 26, _("Done"));
      btn_done_edit->callback((Fl_Callback*)cb_btn_done_edit);
    } // Fl_Button* btn_done_edit
    { btn_cancel_edit = new Fl_Button(465, 276, 65, 26, _("Cancel"));
      btn_cancel_edit->callback((Fl_Callback*)cb_btn_cancel_edit);
    } // Fl_Button* btn_cancel_edit
    { btn_apply_edit = new Fl_Button(465, 305, 65, 26, _("Apply"));
      btn_apply_edit->callback((Fl_Callback*)cb_btn_apply_edit);
    } // Fl_Button* btn_apply_edit
    { new Fl_Box(201, 9, 223, 19, _("Message Text"));
    } // Fl_Box* o
    { new Fl_Box(12, 8, 84, 23, _("Msg Label"));
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(464, 4, 65, 252);
      o->box(FL_ENGRAVED_FRAME);
      { new Fl_Box(469, 7, 54, 20, _("Tags"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 36, 55, 20, _("<CLL>"));
        o->tooltip(_("Your call"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 56, 55, 20, _("<QTH>"));
        o->tooltip(_("Your qth"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 76, 55, 20, _("<LOC>"));
        o->tooltip(_("Your location"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 96, 55, 20, _("<OPR>"));
        o->tooltip(_("Your name"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 115, 55, 20, _("<STA>"));
        o->tooltip(_("Other stations callsign"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 134, 55, 20, _("<NAM>"));
        o->tooltip(_("Other stations name"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 151, 55, 20, _("<#>"));
        o->tooltip(_("Serial OUT"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 170, 55, 20, _("<+>"));
        o->tooltip(_("Increment serial #"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 189, 55, 20, _("<->"));
        o->tooltip(_("Decrement serial #"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 208, 55, 20, _("<LOG>"));
        o->tooltip(_("Append entry to logbook"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(469, 229, 55, 20, _("<X>"));
        o->tooltip(_("Xout text"));
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(529, 4, 65, 252);
      o->box(FL_ENGRAVED_FRAME);
      { new Fl_Box(532, 7, 59, 20, _("ProSign"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 36, 60, 20, _("\" RR"));
        o->tooltip(_(".-..-."));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 56, 60, 20, _("$ SX"));
        o->tooltip(_("...-..-"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 75, 60, 20, _("\' WG"));
        o->tooltip(_(".----."));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 94, 60, 20, _("( KN"));
        o->tooltip(_("-.--."));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 113, 60, 20, _(") KK"));
        o->tooltip(_("-.--.-"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 132, 60, 20, _("+ AR"));
        o->tooltip(_(".-.-."));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 151, 60, 20, _("< AR"));
        o->tooltip(_(".-.-."));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 170, 60, 20, _("> SK"));
        o->tooltip(_("...-.-"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 189, 60, 20, _("= BT"));
        o->tooltip(_("-...-"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 208, 60, 20, _("- DU"));
        o->tooltip(_("-....-"));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(531, 229, 60, 20, _("@@ AC"));
        o->tooltip(_(".--.-."));
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    { label_11 = new Fl_Input2(29, 294, 50, 22, _("11:"));
      label_11->box(FL_DOWN_BOX);
      label_11->color(FL_BACKGROUND2_COLOR);
      label_11->selection_color(FL_SELECTION_COLOR);
      label_11->labeltype(FL_NORMAL_LABEL);
      label_11->labelfont(0);
      label_11->labelsize(14);
      label_11->labelcolor(FL_FOREGROUND_COLOR);
      label_11->align(Fl_Align(FL_ALIGN_LEFT));
      label_11->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_11
    { edit_msg11 = new Fl_Input2(84, 294, 375, 22);
      edit_msg11->box(FL_DOWN_BOX);
      edit_msg11->color(FL_BACKGROUND2_COLOR);
      edit_msg11->selection_color(FL_SELECTION_COLOR);
      edit_msg11->labeltype(FL_NORMAL_LABEL);
      edit_msg11->labelfont(0);
      edit_msg11->labelsize(14);
      edit_msg11->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg11->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg11->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg11
    { label_12 = new Fl_Input2(30, 321, 50, 22, _("12:"));
      label_12->box(FL_DOWN_BOX);
      label_12->color(FL_BACKGROUND2_COLOR);
      label_12->selection_color(FL_SELECTION_COLOR);
      label_12->labeltype(FL_NORMAL_LABEL);
      label_12->labelfont(0);
      label_12->labelsize(14);
      label_12->labelcolor(FL_FOREGROUND_COLOR);
      label_12->align(Fl_Align(FL_ALIGN_LEFT));
      label_12->when(FL_WHEN_RELEASE);
    } // Fl_Input2* label_12
    { edit_msg12 = new Fl_Input2(85, 321, 375, 22);
      edit_msg12->box(FL_DOWN_BOX);
      edit_msg12->color(FL_BACKGROUND2_COLOR);
      edit_msg12->selection_color(FL_SELECTION_COLOR);
      edit_msg12->labeltype(FL_NORMAL_LABEL);
      edit_msg12->labelfont(0);
      edit_msg12->labelsize(14);
      edit_msg12->labelcolor(FL_FOREGROUND_COLOR);
      edit_msg12->align(Fl_Align(FL_ALIGN_LEFT));
      edit_msg12->when(FL_WHEN_RELEASE);
    } // Fl_Input2* edit_msg12
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Input2 *txt_cll=(Fl_Input2 *)0;

static void cb_txt_cll(Fl_Input2*, void*) {
  change_txt_cll();
}

Fl_Input2 *txt_opr=(Fl_Input2 *)0;

static void cb_txt_opr(Fl_Input2*, void*) {
  change_txt_opr();
}

Fl_Input2 *txt_qth=(Fl_Input2 *)0;

static void cb_txt_qth(Fl_Input2*, void*) {
  change_txt_qth();
}

Fl_Input2 *txt_loc=(Fl_Input2 *)0;

static void cb_txt_loc(Fl_Input2*, void*) {
  change_txt_loc();
}

Fl_Button *btn_done_op_dialog=(Fl_Button *)0;

static void cb_btn_done_op_dialog(Fl_Button*, void*) {
  cb_done_op_dialog();
}

Fl_Double_Window* make_operator_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(296, 162, _("Operator Setup"));
    w = o;
    { txt_cll = new Fl_Input2(63, 10, 224, 23, _("<CLL>"));
      txt_cll->tooltip(_("Your callsign"));
      txt_cll->box(FL_DOWN_BOX);
      txt_cll->color(FL_BACKGROUND2_COLOR);
      txt_cll->selection_color(FL_SELECTION_COLOR);
      txt_cll->labeltype(FL_NORMAL_LABEL);
      txt_cll->labelfont(0);
      txt_cll->labelsize(14);
      txt_cll->labelcolor(FL_FOREGROUND_COLOR);
      txt_cll->callback((Fl_Callback*)cb_txt_cll);
      txt_cll->align(Fl_Align(FL_ALIGN_LEFT));
      txt_cll->when(FL_WHEN_RELEASE);
    } // Fl_Input2* txt_cll
    { txt_opr = new Fl_Input2(63, 41, 224, 23, _("<OPR>"));
      txt_opr->box(FL_DOWN_BOX);
      txt_opr->color(FL_BACKGROUND2_COLOR);
      txt_opr->selection_color(FL_SELECTION_COLOR);
      txt_opr->labeltype(FL_NORMAL_LABEL);
      txt_opr->labelfont(0);
      txt_opr->labelsize(14);
      txt_opr->labelcolor(FL_FOREGROUND_COLOR);
      txt_opr->callback((Fl_Callback*)cb_txt_opr);
      txt_opr->align(Fl_Align(FL_ALIGN_LEFT));
      txt_opr->when(FL_WHEN_RELEASE);
    } // Fl_Input2* txt_opr
    { txt_qth = new Fl_Input2(63, 72, 224, 23, _("<QTH>"));
      txt_qth->tooltip(_("Your QTH"));
      txt_qth->box(FL_DOWN_BOX);
      txt_qth->color(FL_BACKGROUND2_COLOR);
      txt_qth->selection_color(FL_SELECTION_COLOR);
      txt_qth->labeltype(FL_NORMAL_LABEL);
      txt_qth->labelfont(0);
      txt_qth->labelsize(14);
      txt_qth->labelcolor(FL_FOREGROUND_COLOR);
      txt_qth->callback((Fl_Callback*)cb_txt_qth);
      txt_qth->align(Fl_Align(FL_ALIGN_LEFT));
      txt_qth->when(FL_WHEN_RELEASE);
    } // Fl_Input2* txt_qth
    { txt_loc = new Fl_Input2(63, 103, 224, 23, _("<LOC>"));
      txt_loc->tooltip(_("Your locator"));
      txt_loc->box(FL_DOWN_BOX);
      txt_loc->color(FL_BACKGROUND2_COLOR);
      txt_loc->selection_color(FL_SELECTION_COLOR);
      txt_loc->labeltype(FL_NORMAL_LABEL);
      txt_loc->labelfont(0);
      txt_loc->labelsize(14);
      txt_loc->labelcolor(FL_FOREGROUND_COLOR);
      txt_loc->callback((Fl_Callback*)cb_txt_loc);
      txt_loc->align(Fl_Align(FL_ALIGN_LEFT));
      txt_loc->when(FL_WHEN_RELEASE);
    } // Fl_Input2* txt_loc
    { btn_done_op_dialog = new Fl_Button(204, 133, 70, 20, _("Done"));
      btn_done_op_dialog->callback((Fl_Callback*)cb_btn_done_op_dialog);
    } // Fl_Button* btn_done_op_dialog
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Int_Input *txt_serial_nbr=(Fl_Int_Input *)0;

static void cb_txt_serial_nbr(Fl_Int_Input*, void*) {
  serial_nbr();
}

Fl_Int_Input *txt_time_span=(Fl_Int_Input *)0;

static void cb_txt_time_span(Fl_Int_Input*, void*) {
  time_span();
}

Fl_Check_Button *btn_zeros=(Fl_Check_Button *)0;

static void cb_btn_zeros(Fl_Check_Button*, void*) {
  zeros();
}

Fl_Check_Button *btn_ck_band=(Fl_Check_Button *)0;

static void cb_btn_ck_band(Fl_Check_Button*, void*) {
  ck_band();
}

Fl_Check_Button *btn_ck_time_span=(Fl_Check_Button *)0;

static void cb_btn_ck_time_span(Fl_Check_Button*, void*) {
  time_span();
}

Fl_Check_Button *btn_dups=(Fl_Check_Button *)0;

static void cb_btn_dups(Fl_Check_Button*, void*) {
  dups();
}

Fl_Button *btn_close_contest=(Fl_Button *)0;

static void cb_btn_close_contest(Fl_Button*, void*) {
  close_contest();
}

Fl_Input *txt_xout=(Fl_Input *)0;

static void cb_txt_xout(Fl_Input* o, void*) {
  progStatus.xout=o->value();
}

Fl_Double_Window* make_contest_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(455, 65, _("Contest"));
    w = o;
    { txt_serial_nbr = new Fl_Int_Input(59, 4, 60, 24, _("Next #"));
      txt_serial_nbr->tooltip(_("Next serial number to be sent"));
      txt_serial_nbr->type(2);
      txt_serial_nbr->callback((Fl_Callback*)cb_txt_serial_nbr);
    } // Fl_Int_Input* txt_serial_nbr
    { txt_time_span = new Fl_Int_Input(205, 4, 60, 24, _("Time Span"));
      txt_time_span->tooltip(_("Min\'s allowed between dups"));
      txt_time_span->type(2);
      txt_time_span->callback((Fl_Callback*)cb_txt_time_span);
    } // Fl_Int_Input* txt_time_span
    { Fl_Check_Button* o = btn_zeros = new Fl_Check_Button(8, 37, 20, 15, _("Zeros ?"));
      btn_zeros->tooltip(_("Send nbr as 0nn if < 100"));
      btn_zeros->down_box(FL_DOWN_BOX);
      btn_zeros->callback((Fl_Callback*)cb_btn_zeros);
      o->value(progStatus.zeros);
    } // Fl_Check_Button* btn_zeros
    { Fl_Check_Button* o = btn_ck_band = new Fl_Check_Button(93, 37, 20, 15, _("Ck Band"));
      btn_ck_band->tooltip(_("Include band for dup check"));
      btn_ck_band->down_box(FL_DOWN_BOX);
      btn_ck_band->callback((Fl_Callback*)cb_btn_ck_band);
      o->value(progStatus.band);
    } // Fl_Check_Button* btn_ck_band
    { Fl_Check_Button* o = btn_ck_time_span = new Fl_Check_Button(178, 37, 20, 15, _("Ck span"));
      btn_ck_time_span->tooltip(_("Include time span for dup check"));
      btn_ck_time_span->down_box(FL_DOWN_BOX);
      btn_ck_time_span->callback((Fl_Callback*)cb_btn_ck_time_span);
      o->value(progStatus.time_span);
    } // Fl_Check_Button* btn_ck_time_span
    { Fl_Check_Button* o = btn_dups = new Fl_Check_Button(263, 37, 20, 15, _("Ck Dups"));
      btn_dups->tooltip(_("Check for duplicates"));
      btn_dups->down_box(FL_DOWN_BOX);
      btn_dups->callback((Fl_Callback*)cb_btn_dups);
      o->value(progStatus.dups);
    } // Fl_Check_Button* btn_dups
    { btn_close_contest = new Fl_Button(374, 34, 70, 20, _("Close"));
      btn_close_contest->callback((Fl_Callback*)cb_btn_close_contest);
    } // Fl_Button* btn_close_contest
    { Fl_Input* o = txt_xout = new Fl_Input(308, 4, 140, 24, _("Xout"));
      txt_xout->tooltip(_("Exchange out (not serial #)"));
      txt_xout->callback((Fl_Callback*)cb_txt_xout);
      o->value(progStatus.xout.c_str());
    } // Fl_Input* txt_xout
    o->end();
  } // Fl_Double_Window* o
  return w;
}
