// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef wkey_dialogs_h
#define wkey_dialogs_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "combo.h"
extern Fl_ComboBox *selectCommPort;
#include <FL/Fl_Input.H>
extern Fl_Input *inpXmlAddress;
extern Fl_Input *inpXmlPort;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *btn_ser_port_ok;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_serial_port_cancel;
Fl_Double_Window* SetupDialog();
#include <FL/Fl_Menu_Bar.H>
#include "FTextView.h"
extern FTextView *txt_sent;
#include "FTextRXTX.h"
extern FTextTX *txt_to_send;
extern Fl_Button *btn_msg1;
extern Fl_Button *btn_msg2;
extern Fl_Button *btn_msg3;
extern Fl_Button *btn_msg4;
extern Fl_Button *btn_msg5;
extern Fl_Button *btn_msg6;
extern Fl_Button *btn_msg7;
extern Fl_Button *btn_msg8;
extern Fl_Button *btn_msg9;
extern Fl_Button *btn_msg10;
extern Fl_Button *btn_msg11;
extern Fl_Button *btn_msg12;
#include <FL/Fl_Box.H>
extern Fl_Box *box_wait;
extern Fl_Box *box_break_in;
extern Fl_Box *box_busy;
extern Fl_Box *box_xoff;
extern Fl_Box *box_keydown;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *btn_use_pot;
#include <FL/Fl_Output.H>
extern Fl_Output *txt_wpm;
#include <FL/Fl_Counter.H>
extern Fl_Counter *cntr_wpm;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *btn_send;
#include <FL/Fl_Group.H>
#include "flinput2.h"
extern Fl_Input2 *txt_sta;
extern Fl_Button *btn_time_on;
extern Fl_Input2 *txt_name;
extern Fl_Input2 *txt_xchg;
extern Fl_Input2 *txt_time_on;
extern Fl_Button *btn_clear;
extern Fl_Output *txt_time_off;
extern Fl_Button *btn_log_it;
extern Fl_Light_Button *btn_tune;
extern Fl_Button *btn_cancel;
extern Fl_Group *xcvr_group;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *btn_vfoA;
extern Fl_Round_Button *btn_vfoB;
#include "FreqControl.h"
extern cFreqControl *xcvr_freq;
extern Fl_ComboBox *opMODE;
extern Fl_ComboBox *opBW1;
extern Fl_ComboBox *opBW2;
extern Fl_Button *btn_Quit;
Fl_Double_Window* WKey_window();
extern unsigned char menu__i18n_done;
extern Fl_Menu_Item menu_[];
#define mnu_exit (menu_+1)
#define mnu_sel_port (menu_+4)
#define mnu_parameters (menu_+5)
#define mnu_messages (menu_+6)
#define mnu_operator (menu_+7)
#define mnu_Logbook (menu_+9)
#define mnu_display_log (menu_+10)
#define mnu_new_log (menu_+11)
#define mnu_open_logbook (menu_+12)
#define mnu_save_logbook (menu_+13)
#define mnu_merge_logbook (menu_+14)
#define mnu_export_adif (menu_+15)
#define mnu_export_logbook_text (menu_+16)
#define mnu_export_logbook_csv (menu_+17)
#define mnu_export_cabrillo (menu_+18)
#define mnu_log_client (menu_+19)
#define mnu_contest (menu_+21)
#define mnu_events (menu_+22)
#define mnu_about (menu_+24)
#define mnu_on_line_help (menu_+25)
extern Fl_Check_Button *btn_swap;
extern Fl_Check_Button *btn_auto_space;
extern Fl_Check_Button *btn_ct_space;
extern Fl_Check_Button *btn_paddledog;
extern Fl_Check_Button *btn_cut_zeronine;
extern Fl_Check_Button *btn_paddle_echo;
extern Fl_Check_Button *btn_serial_echo;
extern Fl_Check_Button *btn_sidetone_on;
extern Fl_Check_Button *btn_tone_on;
extern Fl_Check_Button *btn_ptt_on;
extern Fl_Counter *cntr_min_wpm;
extern Fl_Counter *cntr_rng_wpm;
extern Fl_Counter *cntr_farnsworth;
extern Fl_Counter *cntr_cmd_wpm;
extern Fl_Counter *cntr_ratio;
extern Fl_Counter *cntr_comp;
extern Fl_Counter *cntr_first_ext;
extern Fl_Counter *cntr_sample;
extern Fl_Counter *cntr_weight;
extern Fl_Counter *cntr_leadin;
extern Fl_Counter *cntr_tail;
extern Fl_ComboBox *choice_keyer_mode;
extern Fl_ComboBox *choice_hang;
extern Fl_ComboBox *choice_sidetone;
extern Fl_ComboBox *choice_output_pins;
extern Fl_Button *btn_done_parameters;
extern Fl_Button *btn_read_parameters;
extern Fl_Button *btn_write_parameters;
Fl_Double_Window* make_parameters_dialog();
extern Fl_Input2 *label_1;
extern Fl_Input2 *edit_msg1;
extern Fl_Input2 *label_2;
extern Fl_Input2 *edit_msg2;
extern Fl_Input2 *label_3;
extern Fl_Input2 *edit_msg3;
extern Fl_Input2 *label_4;
extern Fl_Input2 *edit_msg4;
extern Fl_Input2 *label_5;
extern Fl_Input2 *edit_msg5;
extern Fl_Input2 *label_6;
extern Fl_Input2 *edit_msg6;
extern Fl_Input2 *label_7;
extern Fl_Input2 *edit_msg7;
extern Fl_Input2 *label_8;
extern Fl_Input2 *edit_msg8;
extern Fl_Input2 *label_9;
extern Fl_Input2 *edit_msg9;
extern Fl_Input2 *label_10;
extern Fl_Input2 *edit_msg10;
extern Fl_Button *btn_done_edit;
extern Fl_Button *btn_cancel_edit;
extern Fl_Button *btn_apply_edit;
extern Fl_Input2 *label_11;
extern Fl_Input2 *edit_msg11;
extern Fl_Input2 *label_12;
extern Fl_Input2 *edit_msg12;
Fl_Double_Window* make_message_editor();
extern Fl_Input2 *txt_cll;
extern Fl_Input2 *txt_opr;
extern Fl_Input2 *txt_qth;
extern Fl_Input2 *txt_loc;
extern Fl_Button *btn_done_op_dialog;
Fl_Double_Window* make_operator_dialog();
#include <FL/Fl_Int_Input.H>
extern Fl_Int_Input *txt_serial_nbr;
extern Fl_Int_Input *txt_time_span;
extern Fl_Check_Button *btn_zeros;
extern Fl_Check_Button *btn_ck_band;
extern Fl_Check_Button *btn_ck_time_span;
extern Fl_Check_Button *btn_dups;
extern Fl_Button *btn_close_contest;
extern Fl_Input *txt_xout;
Fl_Double_Window* make_contest_dialog();
#endif
